name             'bsc_scheduler'
maintainer       'Nicholas Herson'
maintainer_email 'nicholas.herson@gmail.com'
license          'All rights reserved'
description      'Installs/Configures bsc_scheduler'
long_description 'Installs/Configures bsc_scheduler'
version          '0.1.0'

depends 'ruby'
depends 'git'
depends 'apache2'
depends 'postgresql'
depends 'database'
depends 'simple_iptables'
depends 'application_python'
